### ISSUE TITLE
 'OutageManage' object has no attribute 'initialize_problem'

### ISSUE THREAD

**Issue by ray1006597080** [whoiszyc/IntelliHealer#1]
With the guide of the document, I have successfully installed the package.
However,   'OutageManage' object has no attribute 'initialize_problem' is reported when I excecuate the following code:
problem.initialize_problem(total_time_step)

After I search for the DS_pyomo.py carefully, "OutageManage" class does not contain "initialize_problem".

Could you please help me?

**Comment by whoiszyc** [comment]
Thank you for your feedback. Please follow the updated manual to install the CPLEX 1280. If you still have issues, please let me know. You can find detailed instruction here: https://intellihealer.readthedocs.io/en/latest/install.html

**Comment by whoiszyc** [comment]
The problem is solved.
